# Generated by Django 3.1.4 on 2021-08-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210812_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
