# Generated by Django 3.1.4 on 2021-08-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
